### ISSUE TITLE
Add .jur.pro.br in Private Section

### ISSUE THREAD

**Issue by RegistryPRO** [publicsuffix/list#436] opened 2017-04-17 19:23 UTC
+ // RegistryPRO Brasil : https://jur.pro.br/ 
+ // Submitted by Saymon Rhuano<saymonrhuano@jur.pro.br>
+  jur.pro.br

**Comment by weppos** [comment] 2017-04-18 09:42
Duplicate of https://github.com/publicsuffix/list/issues/324

**Closed by weppos** 2017-04-18 09:42 UTC

**Comment by RegistryPRO** [comment] 2018-02-18 15:09
@weppos The problem is that it was detected in our system, but it is the bug that will be corrected so far Wednesday.

If I try today or I'm not, I'll be able to make the mistake.

**Comment by RegistryPRO** [comment] 2018-02-18 15:13
@weppos Do you have to wait until tomorrow 16PM on Wednesday?

**Comment by RegistryPRO** [comment] 2018-02-18 15:15
@weppos The only problem is will be resolved corrected after 16pm this Wednesday. Only then can confirmation be done!

**Comment by RegistryPRO** [comment] 2018-04-22 22:32
@weppos Can I reopen the request for suffix inclusion using this ticket number?

**Comment by weppos** [comment] 2018-04-23 01:28
See my comment at https://github.com/publicsuffix/list/pull/448
