### ISSUE TITLE
Add no-ip.com domains

### ISSUE THREAD

**Issue by junaariyoshi** [publicsuffix/list#98] opened 2016-01-01 12:24 UTC
Similar to issue #88 for FreeDNS, the same is needed for no-ip.com and their domains to work with let's encrypt. Although I guess no-ip.com would not have that many entries.

As I'm a customer with them I opened a ticket asking for support...

**Comment by junaariyoshi** [comment] 2016-01-01 18:09
Arrrrg overlooked the pending pull request: #64 

So I guess this is almost then resolved :-)

**Comment by weppos** [comment] 2016-01-21 18:46
Duplicate of #64

**Closed by weppos** 2016-01-21 18:46 UTC
Labels: duplicate
