### ISSUE TITLE
testurl.cz

### ISSUE THREAD

**Issue by michalkolar** [publicsuffix/list#175] opened 2016-03-06 19:42 UTC
Hi,

Please add testurl.cz domain to the PSL.

I have just added the TXT record for verification, it might take a couple of minutes to propagate:

dig -t txt +short psl.testurl.cz
"https://github.com/publicsuffix/list/pull/173"

Thanks!

Kolar

**Comment by weppos** [comment] 2016-03-06 19:46
Duplicate of #175

**Closed by weppos** 2016-03-06 19:46 UTC
Labels: duplicate
