### ISSUE TITLE
I am trying to make pull request in order to add domains to PSL, but failed

### ISSUE THREAD

**Issue by JungSJin** [publicsuffix/list#355] opened 2016-12-15 03:42 UTC
Hi 
Please help on this.

In order to make pull request, I did the following things.

1)Clone the repo in local
2)Create a branch out of "master" called "jungjin"
3)modify public_suffix_list.dat by adding the following lines.
// Western Digital Technologies, Inc : https://www.wdc.com
// Submitted by Jung Jin <jungseok.jin@wdc.com>
wdtest6.com
wdtest7.com
wdtest8.com
4) git add/commit and try to push the "jungjin" branch to remote (git@github.com:publicsuffix/list.git), but encountered the following errors.

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --set-upstream origin jungjin:jungjin
Pushing to git@github.com:publicsuffix/list.git

ERROR: Permission to publicsuffix/list.git denied to JungSJin.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please advise me

**Comment by sleevi** [comment] 2016-12-15 05:00
https://help.github.com/articles/fork-a-repo/ provides instructions.

The issue is you're trying to commit to the main repository directly. Don't
do that. Create a fork, commit to your fork, and submit a pull request.

**Comment by weppos** [comment] 2016-12-29 19:35
Closed by #356

**Closed by weppos** 2016-12-29 19:35 UTC
