### ISSUE TITLE
One more

### ISSUE THREAD

**Issue by oleedd** [publicsuffix/list#2230] opened 2024-10-22 09:13 UTC
freedns.afraid.org uses us.to. It is not in the list.
![image](https://github.com/user-attachments/assets/0990dc26-88a0-4b7d-9f33-9e5599a36bd4)

**Comment by wdhdev** [comment] 2024-10-22 09:20
Duplicate of #271, @simon-friedberger please close.

**Comment by oleedd** [comment] 2024-10-22 09:26
But I really need this one domain to be added. Only this one. What to do?

**Comment by wdhdev** [comment] 2024-10-22 09:42
Contact the team at afraid.org. Only the domain owner can add it.

**Comment by oleedd** [comment] 2024-10-22 09:47
Domain owners are not interested in this. They don't need this. I don't know how it can work so.
I doubt that Google and other companies added their domains themselves (there are Google subdomains in the list).

**Comment by wdhdev** [comment] 2024-10-22 10:10
We don't add any domains ourselves. If companies want to be included on the PSL, they have to list themselves, we don't do it for them.

Companies such as Google, have added their domains themselves. (e.g. #830 contains one of the domains Google has added.)

**Closed** 2024-10-22 10:26 UTC
