### ISSUE TITLE
Please add dnshome.de to the list

### ISSUE THREAD

**Issue by blackm** [publicsuffix/list#136] opened 2016-02-09 19:00 UTC
Please add dnshome.de to the list.

dnshome.de is a German dDNS service. Before creating this issue I contacted the owner of the domain dnshome.de and asked for this approval to be added to the list. He has given the approval

Thanks :-)

**Comment by weppos** [comment] 2016-02-10 09:26
Duplicate of #139

**Closed by weppos** 2016-02-10 09:26 UTC
