### ISSUE TITLE
Add .jur.pro.br in Public Suffix List

### ISSUE THREAD

**Issue by ghost** [publicsuffix/list#324] opened 2016-10-26 18:45 UTC
add .jur.pro.br in Publci Suffix List

**Comment by RegistryPRO** [comment] 2016-10-26 18:49
https://domaines.presse.ml/ // Submitted by Jean Turola <saymonrhuano@gmail.com> jur.pro.br

**Comment by sleevi** [comment] 2016-10-27 19:12
Hi there.

It sounds like this is a request to make a change. The process for how to do that is described in our [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), including how to authenticate that you're authorized to make this request, and how to submit a pull request (which you can do right from this web interface!)

Could you read through that and submit a patch? Thanks!

**Comment by RegistryPRO** [comment] 2016-10-27 19:24
*.jur.pro.br
Cookies may be set for foo.bar.jur.pro.br.
Cookies may not be set for bar.jur.pro.br.

**Comment by RegistryPRO** [comment] 2016-10-27 19:28
https://domaines.presse.ml/ // Submitted by Jean Turola <saymonrhuano@gmail.com> jur.pro.br 

*.jur.pro.br
Cookies may be set for foo.bar.jur.pro.br.
Cookies may not be set for bar.jur.pro.br.

**Comment by RegistryPRO** [comment] 2016-10-27 19:30
@sleevi 


https://domaines.presse.ml/ // Submitted by Jean Turola saymonrhuano@gmail.com jur.pro.br

*.jur.pro.br
Cookies may be set for foo.bar.jur.pro.br.
Cookies may not be set for bar.jur.pro.br.

**Comment by sleevi** [comment] 2016-10-27 23:35
I'm sorry, what you've presented is not a patch. Also, as explained in the Guidelines, it's not sufficient just to say you're authorized - you need to demonstrate it via the means described in the Guidelines.

**Comment by RegistryPRO** [comment] 2016-10-28 04:22
@sleevi PATCH:

+// Company : http://www.domaines.presse.ml
+// Submitted by Saymon Rhuano <saymonrhuano@gmail.com>
+jur.pro.br
+foo.jur.pro.br

Validate saymonrhuano@gmail.com email the Public WHOIS in whois.registro.br or gwhois.org

Note .: For being a domain suffix, the expiration date is not disclosed for technical reasons.

**Comment by sleevi** [comment] 2016-10-28 04:45
Again, @RegistryPro, that is not a patch. Also, can you explain why foo is even necessary and how you intend to use it?

**Comment by RegistryPRO** [comment] 2016-10-28 12:08
@sleevi .jur.pro.br areas are dedicated to the legal department professionals in Brazil (jurisdiction).

I read the Guidelines, and saw the example of a patch, and did as was described in the Guidelines.

I do not understand where is wrong.

Excuse me.

I can not find my error in the request to catalog.

**Comment by RegistryPRO** [comment] 2016-10-28 13:30
@sleevi 

+// Company: NIC Presse du Mali/ Domaines.pressse.ml : https://domaines.presse.ml
+// Submitted by Saymon Rhuano <saymonrhuano@gmail.com>
+jur.pro.br
+

**Comment by sleevi** [comment] 2016-10-28 21:16
https://help.github.com/articles/creating-a-pull-request/

**Comment by RegistryPRO** [comment] 2016-10-30 21:40
@sleevi TXT record added to jur.pro.br for confirmation!

**Comment by RegistryPRO** [comment] 2016-11-15 22:26
+// Company : RegistryPRO Brasil: http://www.domaines.presse.ml
+// Submitted by  Jean Turola info@registry.jur.pro.br
+jur.pro.br

**Comment by SuffixJUR** [comment] 2016-12-11 15:36
Add Private Domain Section


+// Company : http://www.registry.jur.pro.br
+// Submitted by Jean Turola <suffix@jur.pro.br>
+jur.pro.br

**Comment by weppos** [comment] 2016-12-11 16:47
Please don't open new tickets. If you want to accelerate the process, make sure to provide a GitHub pull request as suggested by @sleevi

**Comment by rhuano** [comment] 2017-04-17 17:58
@sleevi Is there another way to add the .jur.pro.br suffix without the need to create a Patch? How to authenticate by email, WHOIS and TXT registration?

Thank you

**Comment by weppos** [comment] 2017-04-18 09:45
> @sleevi TXT record added to jur.pro.br for confirmation!

@ghost I don't see them there:

```
$ dig _psl.jur.pro.br TXT

; <<>> DiG 9.11.0-P1 <<>> _psl.jur.pro.br TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 57747
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_psl.jur.pro.br.		IN	TXT

;; AUTHORITY SECTION:
jur.pro.br.		10719	IN	SOA	ns1.hostinger.pt. hostmaster.jur.pro.br. 2017041702 28800 7200 604800 86400

;; Query time: 13 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Tue Apr 18 11:44:58 CEST 2017
;; MSG SIZE  rcvd: 107
```

**Comment by RegistryPRO** [comment] 2017-04-18 13:40
@weppos Added TXT record:

$ Dig TXT _psl.jur.pro.br https://github.com/publicsuffix/list/pull/57747

**Comment by RegistryPRO** [comment] 2017-04-19 19:18
@weppos Is the inclusion of ID 57747 in the TXT record correct?

**Comment by RegistryPRO** [comment] 2017-04-21 23:21
"TXT" DNS records for jur.pro.br:

jur.pro.br.  1800  IN  TXT  "$ dig TXT _psl.jur.pro.br https://github.com/publicsuffix/list/pull/57747"

By: http://manytools.org/network/query-dns-records-online/go

**Comment by RegistryPRO** [comment] 2017-11-16 00:10
@weppos weppos The .jur.pro.br domain can now be added. The TXT values were included.

Could you test?

**Comment by weppos** [comment] 2017-12-11 09:48
Duplicate of #448

**Closed by weppos** 2017-12-11 09:48 UTC
Labels: pending-validation
