### ISSUE TITLE
Add .i2p

### ISSUE THREAD

**Issue by uis246** [publicsuffix/list#1324] opened 2021-05-18 18:37 UTC
.i2p and .b32.i2p
Maybe more. Is b64.i2p exists?

**Comment by dnsguru** [comment] 2021-05-18 21:43
HuH?  That's 8 words (counting hostnames) which may set a record for shortest issue report ever on this project.... but more to the point it is not really clear at all what the issue is.  I'll lean in and bridge that gap because I think I grok.

Is this a request for inclusion?  

The way to do that is to submit a PR.  

There was some time saved, it would be rejected more than likely.

i2p is not on the PSL, and that would disallow subdomains of it from being included.

Please read [guidelines on authentication](https://github.com/publicsuffix/list/wiki/Guidelines#authentication) and [Security Considerations](https://github.com/publicsuffix/list/wiki/Security-Considerations#the-public-suffix-list-adheres-to-icp-3-and-iab-guidance) - the PSL project adheres to ICP-3 on what gets included or rejected.

Time savings seem important, given the amount of effort that went into writing up the issue, so I'll close this - feel free to re-open it with more information if there is something that moves past the requirements on the two URLs above.

**Closed by dnsguru** 2021-05-18 21:43 UTC

**Comment by dnsguru** [comment] 2021-05-18 21:55
This appears Toresque.... Rather than be a total dick and shut this down without a path forward, I read up in i2p - Other helpful reading: #386

.onion got itself included by going through the process of being vetted through the IETF...  That may or may not work as far as moving this forward, but improves the odds.

**Comment by dnsguru** [comment] 2021-05-19 18:32
It appears after a bit more effort here that .i2p was injected (but rejected) in the dialog inside of issue #374 - did the project take the advice and pursue RFC?
