### ISSUE TITLE
Adding "za" as a tld entry even though it only allows registration under second-level domains.

### ISSUE THREAD

**Issue by tajohnson** [publicsuffix/list#529] opened 2017-09-29 00:54 UTC
I understand that za only allows registration under certain second-level domains.  And that's probably why it's not listed in the PSL by itself.

But there are a number of other domains with similar requirements, according to https://wiki.mozilla.org/TLD_List (ao, ar, bn, etc), and those are specifically listed in the PSL.  

So should "za" be listed in there too?

**Comment by daftano** [comment] 2017-09-29 12:09
@tajohnson good catch.
The registry reports them at https://www.zadna.org.za/content/page/domain-information: you could work at your PR from that one.

**Comment by weppos** [comment] 2017-12-04 17:13
From https://www.zadna.org.za/content/page/domain-information/

> ZA supports a second level domain (SLD) structure which means that domain names can only be registered under an SLD e.g. yourname.gov.za or yourname.net.za.

That's the reason the .ZA is not listed. Using the other TLDs are example may be incorrect, as they may accept registrations at the SLD (if they don't, then it's a bug and they have to be updated).

Duplicate of #390

**Closed by weppos** 2017-12-04 17:13 UTC
Labels: invalid
