### ISSUE TITLE
nsw.gov.au (and nt.gov.au) incorrectly commented out

### ISSUE THREAD

**Issue by ynotnswpsl** [publicsuffix/list#788] opened 2019-03-20 21:18 UTC
This domain is most commonly used for two purposes: 

1. Departments (bureaucracies, not electoral subdivisions) of NSW State Government, e.g. transport.nsw.gov.au, service.nsw.gov.au.  Traditionally these each have their own IT infrastructure and administration, though the government has made various efforts to unify, federate, or outsource IT operations over the years.  

2. Local Government Authorities (Councils), e.g. [blacktown.nsw.gov.au](https://www.blacktown.nsw.gov.au), [cityofparramatta.nsw.gov.au](https://www.cityofparramatta.nsw.gov.au/).  These are independent entities, with some oversight by the NSW Office of Local Government ([olg.nsw.gov.au](https://olg.nsw.gov.au/)).  They have their own elected members, operational bureaucracy, and IT infrastructure.  They use various differing providers for DNS hosting, web hosting and email security. 

_(Background: government in Australia has three tiers: "Commonwealth" (federal), State, and local.  The Commonwealth is enabled with a constitution agreed by the States, and local government is enabled by Acts of State Parliaments.)_ 

Whilst there are efforts to develop single sign-on at the state (https://my.service.nsw.gov.au/MyServiceNSW/Register) and federal (myGovID) levels, these should not require setting a supercookie across all NSW or GOV domains.  

auDA (.au Domain Administration Ltd) lists the Commonwealth Digital Transformation Agency (DTA) as the responsible body for the "Closed 2LD" gov.au.
-- https://www.auda.org.au/industry-information/au-domains/

DTA states that "The Registrant must be an organisation established by an Act of Parliament or government regulation as a government **department or agency**; a **local government entity**; a statutory authority; or other defined government body." It also says "Domain names can only be registered using the jurisdictional extension of the Registrant’s jurisdiction.
e.g. NSW Government Registrants can **only register domain names with nsw.gov.au extensions**." [emphasis added]
-- https://www.domainname.gov.au/domain-policies/eligibility-and-allocation-policy 

Clearly, by this example, nsw.gov.au is explicitly intended to be a public suffix.  As is nt.gov.au.

The original change removing nsw.gov.au is light on detail.  It just says that a person at services.nsw.gov.au claimed to represent the whole nsw.gov.au domain.  It would help to know what their job title was and whether they had proper delegation of authority in the matter.  
-- https://bugzilla.mozilla.org/show_bug.cgi?id=547985

Disclosure: I work for an LGA, but do not officially represent them.  I am presenting myself here as a private citizen.  

[edit 2019-03-22 - fixed and inserted links]

**Comment by ynotnswpsl** [comment] 2019-03-22 03:17
When I posted this, GitHub helpfully recommended issues [61](https://github.com/publicsuffix/list/issues/61), [92](https://github.com/publicsuffix/list/issues/92), and [665](https://github.com/publicsuffix/list/issues/665).  

These were all closed without action for similar reasons that I suggest undoing the older changes: insufficient authority of requester, multiple independent subdomains clearly exist.  

Plus, we now have specific guidance from DTA (formerly DTO) website.

**Comment by sleevi** [comment] 2019-03-22 03:25
We would need someone with the appropriate authority - e.g. the DTA or
NSW/NT Governments - to request the addition of those additional domains as
being delegated to/operated by entities under than nsw.gov.au / nt.gov.au

I appreciate you raising this issue, but I hope you can understand that
there are compatibility issues either way. Given we had a previously
authorized request for removal, I think we’d be loathe to reintroduce it
without an appropriate authority commenting, particularly one capable of
investigating the compatibility risk of reintroducing these entries.

**Comment by gordongrace** [comment] 2019-06-07 07:11
I work for the Australian Government [Digital Transformation Agency](https://www.dta.gov.au) as the product owner for [domainname.gov.au](https://www.domainname.gov.au).

By agreement with DTA and [auDA](https://www.auda.org.au), [WHOIS](https://whois.auda.org.au) contact details for the `nt.gov.au`, `sa.gov.au`, `nsw.gov.au`, `act.gov.au`, `tas.gov.au`, `wa.gov.au`, `qld.gov.au` and `vic.gov.au` domains were recently updated to reflect the relevant technical and administration contact points within those respective jurisdictions.

In Australia, each state and territory jurisdiction using the registry has their own eligibility policies and guidance for fourth-level registrants:
https://www.domainname.gov.au/domain-policies

Tasmania and the Northern Territory do **not** currently register their fourth-level domains:
- Fourth-level `nt.gov.au` domains are not currently registered, but this may change in the future, pending discussions between NT, DTA and auDA.
- Fourth-level `tas.gov.au` domains are currently pending migration to the `au` registry.

Please let me know if any additional context or background is required.

**Comment by dnsguru** [comment] 2020-04-04 03:40
@gordongrace @ynotnswpsl Given the intricacies of all discussed within this issue, could we have someone from auDA who is technical work with creating a Pull Request that addresses the changes discussed?  

In the past, we've had conflicting requests and have validated .au requests, so there is a desire to have the entries correct and accurate from an authoritative source, self-submitted.

**Comment by dnsguru** [comment] 2020-04-24 14:53
@gordongrace is this still needed?  I've reached out to .AU and they have hopefully been in touch.

**Comment by gordjw** [comment] 2020-10-08 08:05
Hi @dnsguru and @sleevi,

I've recently taken over from @gordongrace as product owner for domainname.gov.au.

This is an ongoing discussion with NSW, but as far as I know we haven't heard from auDA yet. I'll follow up.

It would be helpful if we could read the original request to remove nsw.gov.au from the PSL. 
There may be some reason this was requested that nobody is currently aware of.
According to https://publicsuffix.org/list/public_suffix_list.dat, that's "Bug 547985 - Removed at request of <Shae.Donelan@services.nsw.gov.au>", from 2010-03-04. 

Is the original CVS entry or email from Shae still around or in an archive somewhere that could be viewed?

**Comment by dnsguru** [comment] 2020-10-08 09:03
Limited history exists before the move to Github in summer of 2015
Did a quick pass search for gov.au on the prior repository and only found these
from 2014
<https://bugzilla.mozilla.org/buglist.cgi?resolution=---&resolution=FIXED&resolution=INVALID&resolution=WONTFIX&resolution=DUPLICATE&resolution=WORKSFORME&resolution=INCOMPLETE&resolution=SUPPORT&resolution=EXPIRED&resolution=MOVED&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&query_format=advanced&short_desc_type=substring&short_desc=gov.au&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&list_id=15442961&product=Core&component=Networking%3A%20Domain%20Lists>,
but not the original submission.
Also found this link in archives:
https://bugzilla.mozilla.org/show_bug.cgi?id=940478  and
https://bugzilla.mozilla.org/show_bug.cgi?id=547985

It appears the initial email went to Gerv Markham, and he's unfortunately
not with us anymore, so the info in that last link is about as good as
you'll get.

You are welcome to sleuth further if you are looking for root cause or
background but I suspect you'd have to dig through Shae's emails

We're volunteer based and focusing on core mission of maintaining list.



Jothan Frakes

**Comment by amitdasdcs** [comment] 2020-10-13 00:56
Hi @dnsguru and @sleevi,
I work for Government of NSW.
I am currently working on a initiative to enable 'nsw.gov.au' in Public Suffix List.
I am in touch with @gordjw from DTA and few other internal stakeholders.
Would you please let me know what need to happen to enable 'nsw.gov.au' in Public Suffix List?

- Who from NSW government need to approve the request?
- Who from auDA need to approve the request?
- How do I raise a ticket for Mozila foundation to get the request actiond?
- How long the fullfilment process take?
- What is the impct on NSW Government domains when we enable 'nsw.gov.au' in Public Suffix List?

Thanks in advance for yoru assistance as I undertand that you guys are volunteer based.

Thanks
Amit.

**Comment by dnsguru** [comment] 2020-10-13 04:31
We're volunteer maintainers, and not resourced to train people or do
walk-throughs... please read the wiki docs and follow them.

Here is a link to them: https://github.com/publicsuffix/list/wiki

Just requires some familiarity with Github and some ability to
verify/validate authority over the namespace you seek to modify or add in
the PSL via DNS

**Comment by gordjw** [comment] 2020-10-16 10:12
Tyvm Jothan, I appreciate you finding the original tickets.

**Comment by akumria** [comment] 2021-07-01 06:39
@gordjw / @amitdasdcs Is there an update / progress that you can share?

I believe you simply need to raise the PR (as documented in Oct 2020) to get this done.

**Comment by wdhdev** [comment] 2024-11-29 07:41
@simon-friedberger This can be closed, the entire .au section was confirmed by auDA in #2267

**Closed** 2024-11-29 08:00 UTC
Labels: waiting-followup

**Comment by dnsguru** [comment] 2024-11-29 12:06
Just please be aware we have historically received conflicting directions from auda and the respective nsw delegees, so remember, if that happens again, to  point the nsw.gov.au requestor at this.
