### ISSUE TITLE
add .ind.mom

### ISSUE THREAD

**Issue by anantsparrow** [publicsuffix/list#1788] opened 2023-06-29 06:48 UTC
Hey there, we are at SparrowHost Registry, launched .ind.mom domains to sell it's 3rd level domains. Kindly add it to the list

**Comment by Fharmon1983** [comment] 2023-06-30 00:45
-

**Comment by Fharmon1983** [comment] 2023-06-30 00:46
https://github.com/publicsuffix/list/issues/1788#issuecomment-1613964545

**Comment by Fharmon1983** [comment] 2023-06-30 00:46
https://github.com/publicsuffix/list/issues/1788#issue-1780233858

**Comment by Fharmon1983** [comment] 2023-06-30 00:46
Kindly ask if can add to list

**Comment by Fharmon1983** [comment] 2023-06-30 00:46
@Fharmon1983

**Comment by Fharmon1983** [comment] 2023-06-30 00:47
#1770

**Comment by Fharmon1983** [comment] 2023-06-30 00:47
Duplicate of #

**Comment by Fharmon1983** [comment] 2023-06-30 00:47
>  #``

**Comment by Fharmon1983** [comment] 2023-06-30 00:47
@danderson

**Comment by dnsguru** [comment] 2023-06-30 01:49
#1789 link

Please note a massive queue ahead of you so give it about 6 months before you prod the volunteers.  Thxbye

**Comment by Fharmon1983** [comment] 2023-06-30 01:52
> 

Hi there we are working on getting what we work for @Fharmon1983

**Comment by anantsparrow** [comment] 2023-06-30 04:57
> #1789 link
> 
> Please note a massive queue ahead of you so give it about 6 months before you prod the volunteers. Thxbye

hi there, so it will take 6 months for .ind.mom to be added to publicsuffix? actually our customers are waiting for this.

**Comment by dnsguru** [comment] 2023-06-30 07:07
We are volunteers on this, investing personal time at this point to maintain the PSL, so things are processed as there is available time.  The request was to be patient and only nag us 6 months from now if this has not been reviewed, and not before that time.  

One thing that you can do which may help reviewers once there is a volunteer cycle available is for your project to list its policies and where it is available for one to obtain an ind.mom domain name, as this was not found.

**Comment by anantsparrow** [comment] 2023-06-30 07:10
> We are volunteers on this, investing personal time at this point to maintain the PSL, so things are processed as there is available time. The request was to be patient and only nag us 6 months from now if this has not been reviewed, and not before that time.
> 
> One thing that you can do which may help reviewers once there is a volunteer cycle available is for your project to list its policies and where it is available for one to obtain an ind.mom domain name, as this was not found.

hey there, we are currently in sunrise period for these domains.

anyone can still book a ind.mom domains through sparrowhost.in website or an accredited registrar of this sld

**Comment by dnsguru** [comment] 2023-06-30 07:37
Congratulations on customers.  It didn't look likely, but if that is honest, great.  

Volunteers on PSL are slammed elsewhere and when there is time to review Pull Requests, there are many others ahead of yours in line, so the 6 months was a polite request to not be pushy, nudge us, or other reminders as they delay the processing of those ahead of you and ... honestly frustrate people who donate their personal time to maintain this.

In reviewing registry.ind.mom website, there are still quite a lot of links that are being connected up, lorem ipsem text and some very obvious signs of it being a rapidly developed work in progress.   By the time PSL review is possible, hopefully this project will be launched and mature will formally have such alleged customers.

Meanwhile the PR needs updating to place it in the appropriately sorted location in the PRIVATE section sorted by company name.  Please see this : https://github.com/publicsuffix/list/wiki/Guidelines#sort-your-submission-correctly-important

Next steps, you'll see a mention (probably) once a merge happens, or a request for a change.  

Right now your pull request is in a fail state - in need of a fix as described in the link.   Remedy that so that when a reviewer can look at the pull request, yours is ready.

In the mean time, go about your business and we'd request low 'reminders' etc out of respect for our time and the ability to process those ahead of you in the queue.

**Comment by anantsparrow** [comment] 2023-06-30 07:40
thank you for your time in reviewing,

what went wrong ?

Meanwhile the PR needs updating to place it in the appropriately sorted location in the PRIVATE section sorted by company name. Please see this : https://github.com/publicsuffix/list/wiki/Guidelines#sort-your-submission-correctly-important

as i can see everything as according to the template of your pr

**Comment by anantsparrow** [comment] 2023-06-30 07:47
// SparrowHost : https://sparrowhost.in/
// Submitted by Anant Pandey <anant@sparrowhost.in>
ind.mom

this format is wrong?

**Comment by anantsparrow** [comment] 2023-06-30 08:03
> 

we are currently modifying the registrar backend portal so few faqs are left on purpose. however if that seems to be important that we are fixing that right now on registry.ind.mom website. meanwhile please let us know what should we change on the PR. i see no issues on that.

**Comment by anantsparrow** [comment] 2023-06-30 08:03
> Congratulations on customers. It didn't look likely, but if that is honest, great.
> 
> Volunteers on PSL are slammed elsewhere and when there is time to review Pull Requests, there are many others ahead of yours in line, so the 6 months was a polite request to not be pushy, nudge us, or other reminders as they delay the processing of those ahead of you and ... honestly frustrate people who donate their personal time to maintain this.
> 
> In reviewing registry.ind.mom website, there are still quite a lot of links that are being connected up, lorem ipsem text and some very obvious signs of it being a rapidly developed work in progress. By the time PSL review is possible, hopefully this project will be launched and mature will formally have such alleged customers.
> 
> Meanwhile the PR needs updating to place it in the appropriately sorted location in the PRIVATE section sorted by company name. Please see this : https://github.com/publicsuffix/list/wiki/Guidelines#sort-your-submission-correctly-important
> 
> Next steps, you'll see a mention (probably) once a merge happens, or a request for a change.
> 
> Right now your pull request is in a fail state - in need of a fix as described in the link. Remedy that so that when a reviewer can look at the pull request, yours is ready.
> 
> In the mean time, go about your business and we'd request low 'reminders' etc out of respect for our time and the ability to process those ahead of you in the queue.

we are currently modifying the registrar backend portal so few faqs are left on purpose. however if that seems to be important that we are fixing that right now on registry.ind.mom website. meanwhile please let us know what should we change on the PR. i see no issues on that.

**Comment by anantsparrow** [comment] 2023-06-30 08:54
> Congratulations on customers. It didn't look likely, but if that is honest, great.
> 
> Volunteers on PSL are slammed elsewhere and when there is time to review Pull Requests, there are many others ahead of yours in line, so the 6 months was a polite request to not be pushy, nudge us, or other reminders as they delay the processing of those ahead of you and ... honestly frustrate people who donate their personal time to maintain this.
> 
> In reviewing registry.ind.mom website, there are still quite a lot of links that are being connected up, lorem ipsem text and some very obvious signs of it being a rapidly developed work in progress. By the time PSL review is possible, hopefully this project will be launched and mature will formally have such alleged customers.
> 
> Meanwhile the PR needs updating to place it in the appropriately sorted location in the PRIVATE section sorted by company name. Please see this : https://github.com/publicsuffix/list/wiki/Guidelines#sort-your-submission-correctly-important
> 
> Next steps, you'll see a mention (probably) once a merge happens, or a request for a change.
> 
> Right now your pull request is in a fail state - in need of a fix as described in the link. Remedy that so that when a reviewer can look at the pull request, yours is ready.
> 
> In the mean time, go about your business and we'd request low 'reminders' etc out of respect for our time and the ability to process those ahead of you in the queue.

thank you for your review, we have finally fixed the error. Kindly remove the fail tag on pull requests

**Comment by dnsguru** [comment] 2023-07-18 20:47
closing this issue as it seems like it will be handled when #1789 is reviewed in the future

**Closed by dnsguru** 2023-07-18 20:47 UTC

**Comment by anantsparrow** [comment] 2023-10-14 10:55
any update regarding this? it's been months
