### ISSUE TITLE
URGENT! AUTOPULL seems to have broken with CDN move to Google

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1696] opened 2023-01-28 00:12 UTC
@cpu 

The ICANN gTLD autopull seems to not be working  

@smarnach could CDN move have broken this?  please test

@sleevi was this tied perhaps to your keys?

**Comment by cpu** [comment] 2023-01-28 00:21
Looking into this.

**Comment by cpu** [comment] 2023-01-28 00:29
I found an email in my inbox from Dec 7th that I missed:

> Hi tld-update-bot,
> 
> We’re writing to let you know that we observed suspicious activity that suggests a threat actor used a Personal Access Token (PAT) associated with your account to access private repository metadata.
> 
> Out of an abundance of caution, we reset your account password and revoked all of your Personal Access Tokens (classic), OAuth App tokens, and GitHub App tokens to protect your account, tld-update-bot.

That looks like the root cause for the invalid credentials error in the workflow. I've been able to log in to the account and set a new password. 

To get the GitHub actions integration working again I need to communicate a new PAT to a maintainer that can update the secret environment variable referenced by the workflow:
> https://github.com/publicsuffix/list/blob/19f2225196dcf2b8f624a279b448eee7894a92b1/.github/workflows/tld-update.yml#L35

@dnsguru Can you do this if I were to send you the PAT over Signal or another out-of-band medium?  IIRC @sleevi did it in for me in the past.

**Comment by cpu** [comment] 2023-01-28 00:41
> I found an email in my inbox from Dec 7th

Further evidence this is the root cause: the last successful run [was also on Dec 7th](https://github.com/publicsuffix/list/actions/runs/3640194923/jobs/6144541355).

**Comment by cpu** [comment] 2023-01-28 00:52
I suspect the PAT was revoked in response to the [Travis CI security breach](https://news.ycombinator.com/item?id=33906591) that happened in early Dec. Before this integration was switched to GitHub actions I was using Travis CI and probably did not rotate the PAT when we set up the GitHub version.

**Comment by weppos** [comment] 2023-01-30 09:29
Fixed by https://github.com/publicsuffix/list/pull/1697

**Closed by weppos** 2023-01-30 09:29 UTC
Labels: ✅ autopull

**Comment by dnsguru** [comment] 2023-01-30 12:55
Thank you @weppos and @cpu
