### ISSUE TITLE
Third level registration .name?

### ISSUE THREAD

**Issue by RegistryPRO** [publicsuffix/list#468] opened 2017-06-16 20:28 UTC
Would it be possible to include the third level registry under the .name gTLD?

The .name gTLD also makes third-level records.

Example: name1.name2.name

**Comment by sleevi** [comment] 2017-06-16 20:31
See PR #277 - and the discussion on there

**Comment by weppos** [comment] 2017-10-16 08:37
Closing as duplicate of #277

**Closed by weppos** 2017-10-16 08:37 UTC
