### ISSUE TITLE
Add New Domain GRU.BR on public_suffix_list

### ISSUE THREAD

**Issue by kutpenco** [publicsuffix/list#502] opened 2017-08-08 20:57 UTC
Hello, Please add the Domain GRU.BR Released on 2018-08-07 12:00 (GMT -03:00) by NIC.BR on Brasil.

Regards, Penco Lucas.

**Comment by kutpenco** [comment] 2017-08-08 21:10
+// add domain by NIC.BR on 2018-08-07 12:00 GMT -3:00
+gru.br
+// end edit, credits Lucas Penco. tks

**Comment by sleevi** [comment] 2017-08-08 21:16
Please see https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by weppos** [comment] 2017-08-09 07:52
Duplicate of #504

**Closed by weppos** 2017-08-09 07:52 UTC
